#FROM xushikuan/alpine-build:1.0
FROM golang:1.13-alpine

ENV WORK_DIR=/app
ENV TIME_ZONE=Asia/Singapore

WORKDIR $WORK_DIR

RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone
RUN apk --update add \
    go \
    musl-dev
RUN apk --update add \
    util-linux-dev

RUN mkdir -p logs
COPY . .
RUN go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o main main.go
#RUN go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" xcgo.go

#COPY main .
#COPY config.conf .
#COPY basic.db ./data
#COPY db db

ENTRYPOINT ./main -c config.conf