version: '3.4'

services:
  mini-mq:
    image: xushikuan/mini-mq:latest
#    image: xushikuan/mini-mq:${APPLICATION_VERSION}
    env_file:
      - ./sillyhat-env-config/config.env
#    volumes:
#      - ./mini-mq/data:/go/data
#      - ./mini-mq/logs:/go/logs
    ports:
      - 8100:8100
      - 8200:8200
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8100/health"]
      start_period: 10s
      timeout: 10s
      retries: 3
      interval: 5s