// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package grpcproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type HelloResponse struct {
	Code                 string              `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Body                 *HelloResponse_User `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Message              string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Extra                string              `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *HelloResponse) GetBody() *HelloResponse_User {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloResponse) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type HelloResponse_User struct {
	UserId               int64                    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string                   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Age                  int32                    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	IsDelete             bool                     `protobuf:"varint,4,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	CreateTime           int64                    `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Msg                  []byte                   `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	AddressList          []*HelloResponse_Address `protobuf:"bytes,7,rep,name=addressList,proto3" json:"addressList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *HelloResponse_User) Reset()         { *m = HelloResponse_User{} }
func (m *HelloResponse_User) String() string { return proto.CompactTextString(m) }
func (*HelloResponse_User) ProtoMessage()    {}
func (*HelloResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1, 0}
}

func (m *HelloResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse_User.Unmarshal(m, b)
}
func (m *HelloResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse_User.Marshal(b, m, deterministic)
}
func (m *HelloResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse_User.Merge(m, src)
}
func (m *HelloResponse_User) XXX_Size() int {
	return xxx_messageInfo_HelloResponse_User.Size(m)
}
func (m *HelloResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse_User proto.InternalMessageInfo

func (m *HelloResponse_User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HelloResponse_User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *HelloResponse_User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *HelloResponse_User) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *HelloResponse_User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *HelloResponse_User) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *HelloResponse_User) GetAddressList() []*HelloResponse_Address {
	if m != nil {
		return m.AddressList
	}
	return nil
}

type HelloResponse_Address struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ZipCode              string   `protobuf:"bytes,3,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	Photo                string   `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
	IsDelete             bool     `protobuf:"varint,5,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse_Address) Reset()         { *m = HelloResponse_Address{} }
func (m *HelloResponse_Address) String() string { return proto.CompactTextString(m) }
func (*HelloResponse_Address) ProtoMessage()    {}
func (*HelloResponse_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1, 1}
}

func (m *HelloResponse_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse_Address.Unmarshal(m, b)
}
func (m *HelloResponse_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse_Address.Marshal(b, m, deterministic)
}
func (m *HelloResponse_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse_Address.Merge(m, src)
}
func (m *HelloResponse_Address) XXX_Size() int {
	return xxx_messageInfo_HelloResponse_Address.Size(m)
}
func (m *HelloResponse_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse_Address.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse_Address proto.InternalMessageInfo

func (m *HelloResponse_Address) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HelloResponse_Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *HelloResponse_Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *HelloResponse_Address) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *HelloResponse_Address) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpcproto.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "grpcproto.HelloResponse")
	proto.RegisterType((*HelloResponse_User)(nil), "grpcproto.HelloResponse.User")
	proto.RegisterType((*HelloResponse_Address)(nil), "grpcproto.HelloResponse.Address")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xfd, 0xd2, 0x24, 0xfd, 0xb9, 0xe9, 0xf7, 0x51, 0x2e, 0x1f, 0x3a, 0x04, 0x94, 0xd0, 0x85,
	0x64, 0x15, 0xb0, 0x3e, 0x80, 0xf8, 0xb3, 0x50, 0x90, 0x2e, 0xa6, 0xfa, 0x00, 0x69, 0x72, 0x69,
	0x03, 0x89, 0x13, 0x67, 0x52, 0xb5, 0x6e, 0x7c, 0x53, 0xd7, 0x3e, 0x86, 0xcc, 0x74, 0x52, 0x5a,
	0xa4, 0xbb, 0x73, 0xee, 0x9c, 0xfb, 0x73, 0x4e, 0x02, 0xa3, 0x25, 0x95, 0xa5, 0x78, 0x13, 0xb2,
	0xcc, 0x93, 0x5a, 0x8a, 0x46, 0xe0, 0x60, 0x21, 0xeb, 0xcc, 0xc0, 0xf1, 0x19, 0x0c, 0xef, 0xf4,
	0x33, 0xa7, 0x97, 0x15, 0xa9, 0x06, 0x8f, 0xa0, 0xbb, 0x52, 0x24, 0xef, 0x73, 0xe6, 0x44, 0x4e,
	0xec, 0x72, 0xcb, 0xc6, 0xdf, 0x2e, 0xfc, 0xb5, 0x42, 0x55, 0x8b, 0x67, 0x45, 0x88, 0xe0, 0x65,
	0x22, 0x27, 0xa3, 0x1b, 0x70, 0x83, 0xf1, 0x1c, 0xbc, 0xb9, 0xc8, 0xd7, 0xac, 0x13, 0x39, 0x71,
	0x30, 0x39, 0x49, 0xb6, 0x7b, 0x92, 0xbd, 0xde, 0xe4, 0x49, 0x91, 0xe4, 0x46, 0x8a, 0x0c, 0x7a,
	0x15, 0x29, 0x95, 0x2e, 0x88, 0xb9, 0x66, 0x52, 0x4b, 0xf1, 0x3f, 0xf8, 0xf4, 0xde, 0xc8, 0x94,
	0x79, 0xa6, 0xbe, 0x21, 0xe1, 0x97, 0x03, 0x9e, 0x6e, 0x3f, 0x74, 0x29, 0x86, 0xd0, 0xd7, 0x68,
	0x9a, 0x56, 0x64, 0xee, 0x18, 0xf0, 0x2d, 0xc7, 0x11, 0xb8, 0xed, 0x22, 0x9f, 0x6b, 0xa8, 0xd5,
	0x85, 0xba, 0xa5, 0x92, 0x1a, 0x32, 0x7b, 0xfa, 0x7c, 0xcb, 0xf1, 0x14, 0x20, 0x93, 0x94, 0x36,
	0xf4, 0x58, 0x54, 0xc4, 0x7c, 0xb3, 0x65, 0xa7, 0xa2, 0xa7, 0x55, 0x6a, 0xc1, 0xba, 0x91, 0x13,
	0x0f, 0xb9, 0x86, 0x78, 0x0d, 0x41, 0x9a, 0xe7, 0x92, 0x94, 0x7a, 0x28, 0x54, 0xc3, 0x7a, 0x91,
	0x1b, 0x07, 0x93, 0xe8, 0x60, 0x0c, 0x57, 0x1b, 0x2d, 0xdf, 0x6d, 0x0a, 0x3f, 0xa1, 0x67, 0xeb,
	0xf8, 0x0f, 0x3a, 0x45, 0x6b, 0xaf, 0x53, 0xe4, 0x3a, 0x2b, 0xab, 0xb4, 0xce, 0x5a, 0xaa, 0x5f,
	0x3e, 0x8a, 0xfa, 0x46, 0x7f, 0x0f, 0x9b, 0xa2, 0xa5, 0x3a, 0xc5, 0x7a, 0x29, 0x1a, 0xd1, 0xa6,
	0x68, 0xc8, 0x9e, 0x6d, 0x7f, 0xdf, 0xf6, 0x64, 0x0a, 0x81, 0x0e, 0x78, 0x46, 0xf2, 0xb5, 0xc8,
	0x08, 0x2f, 0xa1, 0x3f, 0x4b, 0xd7, 0xe6, 0x70, 0x3c, 0xfe, 0x6d, 0xc5, 0xfc, 0x36, 0x21, 0x3b,
	0xe4, 0x71, 0xfc, 0x67, 0xde, 0x35, 0xe5, 0x8b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x29,
	0xcd, 0x22, 0x88, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/grpcproto.UserService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.UserService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _UserService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
